[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/bare/*"
  to = "/.netlify/functions/bare/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bare"
  to = "/.netlify/functions/bare"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"
